// ===========================
// VOICE / LANGUAGE PRACTICE AI
// ===========================
let isRecording = false, conversationHistory = [], currentLanguage = 'english', isMuted = false, callStartTime = null, callDurationInterval = null, mediaRecorder = null, audioChunks = [], audioStream = null;
const topics = { english: [{ id: 'intro', label: 'Self Introduction', color: 'blue' }, { id: 'daily', label: 'Daily Routine', color: 'green' }, { id: 'hobbies', label: 'Hobbies & Interests', color: 'yellow' }, { id: 'education', label: 'Education & Career', color: 'purple' }, { id: 'travel', label: 'Travel & Places', color: 'cyan' }, { id: 'random', label: '🎲 Random Topic', color: 'emerald' }], urdu: [{ id: 'intro', label: 'اپنا تعارف', color: 'blue' }, { id: 'daily', label: 'روزمرہ کے کام', color: 'green' }, { id: 'family', label: 'خاندان', color: 'pink' }, { id: 'education', label: 'تعلیم', color: 'purple' }, { id: 'culture', label: 'ثقافت', color: 'yellow' }, { id: 'random', label: '🎲 کوئی بھی موضوع', color: 'emerald' }] };
const topicPrompts = { english: { intro: "Tell me about yourself.", daily: "Describe your typical day.", hobbies: "What are your hobbies?", education: "What are you studying?", travel: "Have you traveled anywhere?", random: "" }, urdu: { intro: "اپنے بارے میں بتائیں۔", daily: "اپنے روز مرہ کے معمولات بیان کریں۔", family: "اپنے خاندان کے بارے میں بتائیں۔", education: "آپ کیا پڑھ رہے ہیں؟", culture: "پاکستانی ثقافت کے بارے میں بتائیں۔", random: "" } };
function selectLanguage(lang) { currentLanguage = lang; document.getElementById('langEnglish').className = lang === 'english' ? 'language-btn active p-3 rounded-xl border-2 border-blue-500 bg-blue-500/20 text-white font-bold text-sm active:scale-95 transition-all' : 'language-btn p-3 rounded-xl border-2 border-zinc-700 bg-zinc-800/20 text-zinc-400 font-bold text-sm active:scale-95 transition-all'; const langUrdu = document.getElementById('langUrdu'); if (langUrdu) langUrdu.className = lang === 'urdu' ? 'language-btn active p-3 rounded-xl border-2 border-blue-500 bg-blue-500/20 text-white font-bold text-sm active:scale-95 transition-all' : 'language-btn p-3 rounded-xl border-2 border-zinc-700 bg-zinc-800/20 text-zinc-400 font-bold text-sm active:scale-95 transition-all'; document.getElementById('coachName').textContent = lang === 'english' ? 'English Coach' : 'اردو کوچ'; loadTopics(); clearConversation(); }
function loadTopics() { const container = document.getElementById('topicButtons'); container.innerHTML = ''; topics[currentLanguage].forEach(topic => { const btn = document.createElement('button'); btn.onclick = () => startTopic(topic.id); btn.className = `px-3 py-2 bg-${topic.color}-500/20 text-${topic.color}-400 border border-${topic.color}-500/30 rounded-lg text-xs font-medium hover:bg-${topic.color}-500/30 active:scale-95 transition-all`; btn.textContent = topic.label; container.appendChild(btn); }); }
function animateSpeaking(speaking) { const mouth = document.getElementById('mouth'); const indicator = document.getElementById('speakingIndicator'); if (speaking) { mouth.style.height = '30px'; indicator.classList.remove('hidden'); } else { mouth.style.height = '20px'; indicator.classList.add('hidden'); } }
function blinkEyes() { const lE = document.getElementById('leftEye'); const rE = document.getElementById('rightEye'); if (!lE || !rE) return; lE.style.height = '2px'; rE.style.height = '2px'; setTimeout(() => { lE.style.height = '16px'; rE.style.height = '16px'; }, 150); }
function showSubtitle(text) { const s = document.getElementById('subtitles'); document.getElementById('subtitleText').textContent = text; s.classList.remove('hidden'); setTimeout(() => s.classList.add('hidden'), 3000); }
function startCallDuration() { callStartTime = Date.now(); callDurationInterval = setInterval(() => { const e = Math.floor((Date.now() - callStartTime) / 1000); document.getElementById('callDuration').textContent = `${Math.floor(e / 60).toString().padStart(2, '0')}:${(e % 60).toString().padStart(2, '0')}`; }, 1000); }
function endCall() { if (callDurationInterval) { clearInterval(callDurationInterval); callDurationInterval = null; } stopRecording(); if (audioStream) { audioStream.getTracks().forEach(t => t.stop()); audioStream = null; } clearConversation(); document.getElementById('callDuration').textContent = '00:00'; }
function muteToggle() { isMuted = !isMuted; const btn = document.getElementById('muteBtn'); if (isMuted) { btn.innerHTML = '<i class="fa-solid fa-volume-xmark"></i>'; btn.className = 'px-4 bg-red-500 text-white rounded-xl active:scale-95 transition-transform'; } else { btn.innerHTML = '<i class="fa-solid fa-volume-high"></i>'; btn.className = 'px-4 bg-zinc-700 text-white rounded-xl active:scale-95 transition-transform'; } }
async function toggleVoiceRecording() { if (!callStartTime) startCallDuration(); if (isRecording) { stopRecording(); } else { await startRecording(); } }
async function startRecording() { try { if (!audioStream) { audioStream = await navigator.mediaDevices.getUserMedia({ audio: true }); } } catch (e) { alert("Microphone access denied. Please grant permission."); return; } audioChunks = []; try { mediaRecorder = new MediaRecorder(audioStream); } catch (e) { alert("Audio recording not supported."); return; } mediaRecorder.ondataavailable = e => { if (e.data.size > 0) audioChunks.push(e.data); }; mediaRecorder.onstop = async () => { if (audioChunks.length === 0) return; const format = mediaRecorder.mimeType || 'audio/webm'; const audioBlob = new Blob(audioChunks, { type: format }); await processAudioWithGroq(audioBlob); }; try { mediaRecorder.start(); isRecording = true; const btn = document.getElementById('voiceBtn'); btn.className = 'flex-1 bg-gradient-to-r from-red-500 to-pink-500 text-white font-bold py-3 rounded-xl shadow-lg active:scale-95 transition-transform flex items-center justify-center gap-2 animate-pulse'; document.getElementById('voiceIcon').className = 'fa-solid fa-microphone-slash'; document.getElementById('voiceBtnText').textContent = 'Recording...'; showSubtitle('Recording your voice...'); } catch (e) { stopRecording(); } }
function stopRecording() { isRecording = false; const btn = document.getElementById('voiceBtn'); btn.className = 'flex-1 bg-gradient-to-r from-green-500 to-emerald-500 text-white font-bold py-3 rounded-xl shadow-lg active:scale-95 transition-transform flex items-center justify-center gap-2'; document.getElementById('voiceIcon').className = 'fa-solid fa-microphone'; document.getElementById('voiceBtnText').textContent = 'Start Speaking'; if (mediaRecorder && mediaRecorder.state === 'recording') { mediaRecorder.stop(); } }
async function processAudioWithGroq(audioBlob) { document.getElementById('connectionStatus').textContent = 'Transcribing...'; showSubtitle('Processing speech...'); try { const formData = new FormData(); let ext = 'webm'; if (audioBlob.type.includes('mp4')) ext = 'm4a'; if (audioBlob.type.includes('ogg')) ext = 'ogg'; formData.append("file", audioBlob, `audio.${ext}`); formData.append("model", "whisper-large-v3-turbo"); formData.append("language", currentLanguage === 'english' ? "en" : "ur"); const res = await fetch("/api/ai/transcribe", { method: "POST", body: formData }); if (!res.ok) throw new Error("Transcribe Fail"); const data = await res.json(); if (data.text && data.text.trim().length > 0) { await handleUserSpeech(data.text.trim()); } else { showSubtitle("I didn't catch that. Please try again!"); document.getElementById('connectionStatus').textContent = 'Connected'; } } catch (e) { showSubtitle("Error catching audio."); document.getElementById('connectionStatus').textContent = 'Connected'; } }
async function handleUserSpeech(text) { addUserMessage(text); showSubtitle(text); document.getElementById('connectionStatus').textContent = 'Thinking...'; try { const response = await getAIVoiceResponse(text); addAIMessage(response); if (!isMuted) { showSubtitle(response); animateSpeaking(true); speakText(response); setTimeout(() => animateSpeaking(false), response.length * 50); } } catch (e) { addAIMessage("Sorry, I'm having trouble. Please try again!"); } document.getElementById('connectionStatus').textContent = 'Connected'; }
async function getAIVoiceResponse() {
    const systemPrompt = currentLanguage === 'english' ?
        "You are an expert English language coach. CRITICAL RULE: If the user makes ANY grammatical mistakes in their sentence, you MUST politely correct their grammar first before answering. Then, keep the conversation flowing smoothly by asking a short follow-up question. Keep total responses under 40 words." :
        "آپ ایک ماہر اردو استاد ہیں۔ اہم नियम: اگر صارف اپنے جملے میں کوئی گرامر کی غلطی کرتا ہے، تو آپ کو سب سے پہلے شائستگی سے اس کی اصلاح کرنی ہوگی۔ پھر گفتگو کو جاری رکھنے کے لیے ایک چھوٹا سا سوال پوچھیں۔ جوابات 40 الفاظ سے کم رکھیں۔";
    const apiMessages = [{ role: "system", content: systemPrompt }]; conversationHistory.forEach(msg => apiMessages.push(msg)); try { const response = await fetch("/api/ai/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: apiMessages, model: "llama-3.1-8b-instant", temperature: 0.7, max_tokens: 150 }) }); const data = await response.json(); return data.choices[0].message.content.trim(); } catch (e) { return currentLanguage === 'english' ? "That's interesting! Tell me more." : "یہ دلچسپ ہے! مزید بتائیں۔"; }
}
function speakText(text) { if ('speechSynthesis' in window) { speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(text); u.lang = currentLanguage === 'english' ? 'en-US' : 'ur-PK'; u.rate = 0.9; speechSynthesis.speak(u); } }
function addUserMessage(text) { conversationHistory.push({ role: 'user', content: text }); const box = document.getElementById('conversationBox'); if (box.children.length === 1 && box.children[0].tagName === 'P') box.innerHTML = ''; const d = document.createElement('div'); d.className = 'bg-blue-500/10 border border-blue-500/20 rounded-lg p-2'; d.innerHTML = `<p class="text-[10px] text-blue-400 font-bold mb-1">You</p><p class="text-xs text-white">${escapeHtml(text)}</p>`; box.appendChild(d); box.scrollTop = box.scrollHeight; }
function addAIMessage(text) { conversationHistory.push({ role: 'assistant', content: text }); const box = document.getElementById('conversationBox'); const d = document.createElement('div'); d.className = 'bg-purple-500/10 border border-purple-500/20 rounded-lg p-2'; d.innerHTML = `<p class="text-[10px] text-purple-400 font-bold mb-1">Coach</p><p class="text-xs text-white">${escapeHtml(text)}</p>`; box.appendChild(d); box.scrollTop = box.scrollHeight; }
function startTopic(topicId) {
    let prompt = topicPrompts[currentLanguage][topicId];
    if (topicId === 'random') {
        const arr = currentLanguage === 'english' ?
            ["Let's talk about your favorite movie or book. What is it and why?", "If you could travel absolutely anywhere in the world, where would it be and why?", "Let's discuss technology. How has it changed your life?", "What is your ultimate dream job and why?", "Tell me about a memorable moment from your childhood.", "Let's talk about a new skill you want to learn."] :
            ["اپنی پسندیدہ فلم یا کتاب کے بارے میں بتائیں۔", "اگر آپ دنیا میں کہیں بھی سفر کر سکیں تو وہ کون سی جگہ ہوگی؟", "ٹیکنالوجی کے بارے میں بات کرتے ہیں۔ اس نے آپ کی زندگی کو کیسے بدلا ہے؟", "آپ کی خوابوں کی نوکری کون سی ہے؟"];
        prompt = arr[Math.floor(Math.random() * arr.length)];
    }
    addAIMessage(prompt); if (!isMuted) { showSubtitle(prompt); speakText(prompt); }
}
function clearConversation() { conversationHistory = []; document.getElementById('conversationBox').innerHTML = '<p class="text-xs text-zinc-500 text-center">Conversation will appear here...</p>'; }
